# Generated by Django 4.0.10 on 2023-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrpColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
