# Generated by Django 4.0.10 on 2023-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0002_srpcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrpPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(default=0)),
                ('ship_name', models.CharField(max_length=255)),
                ('payout', models.IntegerField(default=0)),
            ],
        ),
    ]
