# Generated by Django 4.0.10 on 2023-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0003_srppayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrpShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_id', models.IntegerField(default=0, unique=True)),
                ('ship_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
