# Generated by Django 4.0.10 on 2023-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0004_srpship'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
