# Generated by Django 4.0.10 on 2023-08-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0007_column_alter_cell_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cells', to='dynamicsrp.column'),
        ),
    ]
