# Generated by Django 4.0.10 on 2023-08-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0009_delete_celldata_delete_srpcolumn_delete_srppayout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Row',
            new_name='Ship',
        ),
    ]
