# Generated by Django 4.0.10 on 2023-08-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0010_rename_row_ship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='Reimbursement',
        ),
    ]
