# Generated by Django 4.0.10 on 2023-08-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0011_rename_column_reimbursement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cell',
            new_name='Payout',
        ),
    ]
