# Generated by Django 4.0.10 on 2023-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0012_rename_cell_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_id',
            field=models.IntegerField(default=0),
        ),
    ]
