# Generated by Django 4.0.10 on 2023-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0013_ship_ship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='content',
            field=models.IntegerField(default=0),
        ),
    ]
