# Generated by Django 4.0.10 on 2023-08-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0014_alter_payout_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='content',
            new_name='value',
        ),
    ]
