# Generated by Django 4.0.10 on 2023-08-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0015_rename_content_payout_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='row',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cells', to='dynamicsrp.ship'),
        ),
    ]
