# Generated by Django 4.0.10 on 2023-08-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0016_alter_payout_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='column',
            new_name='reimbursement',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='row',
            new_name='ship',
        ),
    ]
