# Generated by Django 4.0.10 on 2023-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0018_alter_reimbursement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
