# Generated by Django 4.0.10 on 2023-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0019_alter_ship_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
