# Generated by Django 4.0.10 on 2023-08-12 12:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0022_alter_payout_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
