# Generated by Django 4.0.10 on 2023-08-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0024_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('payouts_access', 'Can access the payout page'), ('reports_access', 'Can access the reports page'), ('requests_access', 'Can submit requests and access their requests'))},
        ),
    ]
