# Generated by Django 4.0.10 on 2023-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicsrp', '0025_alter_general_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPRequest',
            fields=[
                ('killmail_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('killmail_time', models.DateTimeField()),
                ('ship_id', models.IntegerField(default=0)),
                ('character_id', models.IntegerField(default=0)),
                ('character_name', models.CharField(max_length=255)),
                ('corporation_id', models.IntegerField(default=0)),
                ('corporation_name', models.CharField(max_length=255)),
                ('alliance_id', models.IntegerField(default=0)),
                ('alliance_name', models.CharField(max_length=255)),
                ('solar_system_id', models.IntegerField(default=0)),
                ('broadcast', models.CharField(max_length=1023)),
            ],
        ),
    ]
